travis:
  secure:
    BINSTAR_TOKEN: LsiQAh5Cyh3gpti4SwYIOKWVgUgAmuHTKSg9vvPU7oOAegUUW4LgiH4EXmKGiOrIIVOevs1K9w83WHdSuSedE8ma0f6lMsQM7O90mIPvIOMIEc3WjnmN96WwH9TU6W9MrumD5qMXgujT8Rt5mwdAf57BFhB7qTZ26/7Luho+c1pPfMvdWXfu+wqdnSzA+0D1kyFC+1mpI5cjAH79EAGfQf/Rt1vROMRznu8pp+1wwcbVKTLoha1vZ2kX3Ahf20NkVuqVdjiQdg8WOjKXwDHoL6dxDmFw++HZos//Yap0ll8eY4HC4eDQS8zTTtOhB2dic2NtFXKoOCqwoXZw7ecyyDGg+k7mIieh7Yh4ePuawtAMt36cT8ssCjtOLJk/hrVuIVrdTOE4qzUQNTEf3kmF4caeezTn6B/vqNfQ94pa7hsJzU8Xl4J1b/OxaE45AzBrI+P3T/ccDpwH7vzb7VufBfgLa5zy6f6axrQNamLfkbVmqHYg/k2zq/46z4VIr8VfpQG4VOptd1BLwgPIaWSQAJbhjWarLwOebq7L6flvU2lROBr4N62cPrTlxeEstTgHIOr6/GsTTX5AWdADLX5kG8mDv//rd1eNEARBgnuuMcgcFOHSD8XQFT3yjGqkxKECvPmwYgPRymfpB0eqaT9RDH+Excis6FqEh6vj64kM9LA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
